version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: thursday
      time: "09:00"
      timezone: UTC
    open-pull-requests-limit: 10
    groups:
      nuget-weekly:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
      day: thursday
      time: "09:00"
      timezone: UTC
    open-pull-requests-limit: 10
    groups:
      npm-weekly:
        applies-to: version-updates
        patterns:
          - "*"
