<Project Sdk="Aspire.AppHost.Sdk/13.3.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>47dc11cd-fb0f-41a7-9ff4-733c43119fbd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ScrumPoker.API\ScrumPoker.API.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Redis" />
  </ItemGroup>

</Project>
