<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Aspire.Hosting.Redis" Version="13.3.5" />
    <PackageVersion Include="Aspire.StackExchange.Redis" Version="13.3.5" />
    <PackageVersion Include="AspNetCore.SwaggerUI.Themes" Version="3.0.2" />
    <PackageVersion Include="FluentValidation.AspNetCore" Version="11.3.0" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.6.0" />
    <PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="10.6.0" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.3" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.15.3" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.15.2" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.15.1" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.15.1" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="10.1.7" />
    <PackageVersion Include="WolverineFx" Version="5.39.3" />
  </ItemGroup>
</Project>
