---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "scrumpoker-api-deployment"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "scrumpoker-api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Chart.Name }}"
        app.kubernetes.io/component: "scrumpoker-api"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - image: "{{ .Values.parameters.scrumpoker_api.scrumpoker_api_image }}"
          name: "scrumpoker-api"
          envFrom:
            - configMapRef:
                name: "scrumpoker-api-config"
            - secretRef:
                name: "{{ .Values.secrets.existingApiSecret | default "scrumpoker-api-secrets" }}"
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: {{ .Values.parameters.scrumpoker_api.port_http | int }}
          imagePullPolicy: "IfNotPresent"
          livenessProbe:
            httpGet:
              path: /alive
              port: {{ .Values.parameters.scrumpoker_api.port_http | int }}
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.parameters.scrumpoker_api.port_http | int }}
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Chart.Name }}"
      app.kubernetes.io/component: "scrumpoker-api"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  replicas: {{ .Values.parameters.scrumpoker_api.replicas | int }}
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
