{{- if not .Values.secrets.existingApiSecret }}
---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "scrumpoker-api-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "scrumpoker-api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__redis: "redis-service:6379,password={{ .Values.secrets.scrumpoker_api.redis_password }}"
  REDIS_PASSWORD: "{{ .Values.secrets.scrumpoker_api.redis_password }}"
  REDIS_URI: "redis://:{{ .Values.secrets.scrumpoker_api.redis_password }}@redis-service:6379"
type: "Opaque"
{{- end }}
