apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: scrum-poker
  labels:
    app: scrum-poker
    component: redis
spec:
  type: ClusterIP
  selector:
    app: scrum-poker
    component: redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
