<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TngTech.ArchUnitNET.xUnitV3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\ScrumPoker.API\ScrumPoker.API.csproj" />
    <ProjectReference Include="..\..\..\src\ScrumPoker.Application\ScrumPoker.Application.csproj" />
    <ProjectReference Include="..\..\..\src\ScrumPoker.Domain\ScrumPoker.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\ScrumPoker.Infrastructure\ScrumPoker.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\src\ScrumPoker.Persistence\ScrumPoker.Persistence.csproj" />
  </ItemGroup>

</Project>
