apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrumpoker-api
  namespace: scrum-poker
  labels:
    app: scrum-poker
    component: scrumpoker-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: scrum-poker
      component: scrumpoker-api
  template:
    metadata:
      labels:
        app: scrum-poker
        component: scrumpoker-api
    spec:
      containers:
        - name: scrumpoker-api
          image: ghcr.io/spicycoder/scrumpoker-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          startupProbe:
            httpGet:
              path: /api/warmup
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 15
            failureThreshold: 30
          envFrom:
            - configMapRef:
                name: scrumpoker-api-config
            - secretRef:
                name: scrum-poker-api-secret
          livenessProbe:
            httpGet:
              path: /alive
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
