apiVersion: v1
kind: Service
metadata:
  name: scrumpoker-api-service
  namespace: scrum-poker
  labels:
    app: scrum-poker
    component: scrumpoker-api
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  selector:
    app: scrum-poker
    component: scrumpoker-api
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
