apiVersion: "v2"
name: "scrum-poker"
version: "1.0.0"
kubeVersion: ">= 1.18.0-0"
description: "Aspire Helm Chart"
type: "application"
keywords:
  - "aspire"
  - "kubernetes"
appVersion: "1.0.0"
deprecated: false
