<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ScrumPoker.API\ScrumPoker.API.csproj" />
  </ItemGroup>

</Project>
