{{- if not .Values.secrets.existingRedisSecret }}
---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "redis-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "redis"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  REDIS_PASSWORD: "{{ .Values.secrets.redis.redis_password }}"
type: "Opaque"
{{- end }}
