---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "redis-service"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "redis"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "redis"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  ports:
    - name: "tcp"
      protocol: "TCP"
      port: 6379
      targetPort: 6379
