apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: scrum-poker
  labels:
    app: scrum-poker
    component: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scrum-poker
      component: web
  template:
    metadata:
      labels:
        app: scrum-poker
        component: web
    spec:
      containers:
        - name: web
          image: ghcr.io/spicycoder/scrumpoker-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              protocol: TCP
              containerPort: 5000
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
