---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "web-config"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "web"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  NODE_ENV: "{{ .Values.config.web.NODE_ENV }}"
  PORT: "{{ .Values.config.web.PORT }}"
  SCRUMPOKER_API_HTTP: "http://scrumpoker-api-service:{{ .Values.parameters.scrumpoker_api.port_http }}"
  services__scrumpoker-api__http__0: "http://scrumpoker-api-service:{{ .Values.parameters.scrumpoker_api.port_http }}"
  SCRUMPOKER_API_HTTPS: "https://scrumpoker-api-service:{{ .Values.parameters.scrumpoker_api.port_http }}"
  YARP_ENABLE_STATIC_FILES: "{{ .Values.config.web.YARP_ENABLE_STATIC_FILES }}"
  OTEL_EXPORTER_OTLP_ENDPOINT: "{{ .Values.config.web.OTEL_EXPORTER_OTLP_ENDPOINT }}"
  OTEL_EXPORTER_OTLP_PROTOCOL: "{{ .Values.config.web.OTEL_EXPORTER_OTLP_PROTOCOL }}"
  OTEL_SERVICE_NAME: "{{ .Values.config.web.OTEL_SERVICE_NAME }}"
